// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKtw93ApW2VT5G8McAW_dQ-PMt1tVP4uk',
    appId: '1:407079940339:web:007a5b054e53a440bd4786',
    messagingSenderId: '407079940339',
    projectId: 'onlinenotes-e7b28',
    authDomain: 'onlinenotes-e7b28.firebaseapp.com',
    storageBucket: 'onlinenotes-e7b28.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChpiEbfusbxMR5XKy6llir9j5cM4svT0c',
    appId: '1:407079940339:android:89399f5dc103c0d5bd4786',
    messagingSenderId: '407079940339',
    projectId: 'onlinenotes-e7b28',
    storageBucket: 'onlinenotes-e7b28.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8KylnVtwoVWwriLgJ6HyIHmBlktekyLU',
    appId: '1:407079940339:ios:b4652e8e94ad3bf6bd4786',
    messagingSenderId: '407079940339',
    projectId: 'onlinenotes-e7b28',
    storageBucket: 'onlinenotes-e7b28.firebasestorage.app',
    iosBundleId: 'com.example.notesOnline',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8KylnVtwoVWwriLgJ6HyIHmBlktekyLU',
    appId: '1:407079940339:ios:b4652e8e94ad3bf6bd4786',
    messagingSenderId: '407079940339',
    projectId: 'onlinenotes-e7b28',
    storageBucket: 'onlinenotes-e7b28.firebasestorage.app',
    iosBundleId: 'com.example.notesOnline',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKtw93ApW2VT5G8McAW_dQ-PMt1tVP4uk',
    appId: '1:407079940339:web:52ac5c54e7742616bd4786',
    messagingSenderId: '407079940339',
    projectId: 'onlinenotes-e7b28',
    authDomain: 'onlinenotes-e7b28.firebaseapp.com',
    storageBucket: 'onlinenotes-e7b28.firebasestorage.app',
  );
}
